/**
 * @file usb_cdc.c
 * @brief USB CDC implementation stub for F103.
 *
 * In production, this is generated by STM32CubeMX (USB CDC ACM class).
 * The stub provides a ring-buffer interface for protocol handler integration.
 */

#include "usb_cdc.h"

#define CDC_TX_BUF 512
#define CDC_RX_BUF 256

static uint8_t tx_buf[CDC_TX_BUF];
static volatile uint16_t tx_head = 0, tx_tail = 0;

static uint8_t rx_buf[CDC_RX_BUF];
static volatile uint16_t rx_head = 0, rx_tail = 0;

void usb_cdc_init(void) {
    tx_head = tx_tail = 0;
    rx_head = rx_tail = 0;
    /* MX_USB_DEVICE_Init() — generated by CubeMX */
}

void usb_cdc_write_byte(uint8_t byte) {
    uint16_t next = (tx_head + 1) % CDC_TX_BUF;
    if (next == tx_tail) return;
    tx_buf[tx_head] = byte;
    tx_head = next;
    /* Trigger IN endpoint if buffer was empty */
}

int usb_cdc_read_byte(uint8_t *byte) {
    if (rx_tail == rx_head) return 0;
    *byte = rx_buf[rx_tail];
    rx_tail = (rx_tail + 1) % CDC_RX_BUF;
    return 1;
}

int usb_cdc_available(void) {
    return (rx_head != rx_tail);
}

/* CDC receive callback (from USB IRQ — fills ring buffer) */
void usb_cdc_rx_callback(const uint8_t *data, uint16_t len) {
    for (uint16_t i = 0; i < len; i++) {
        uint16_t next = (rx_head + 1) % CDC_RX_BUF;
        if (next == rx_tail) break; /* overflow */
        rx_buf[rx_head] = data[i];
        rx_head = next;
    }
}
