"""中英文字符串 — 直接查表，无翻译框架。"""

ZH = {
    "title": "open-canoe",
    "connect": "连接",
    "disconnect": "断开",
    "connecting": "连接中...",
    "connected": "● 已连接",
    "disconnected": "● 未连接",
    "mcu": "MCU 型号",
    "com_port": "COM 端口",
    "connection": "连接",
    "can_settings": "CAN 设置",
    "bitrate": "波特率",
    "silent": "静默模式（仅监听）",
    "loopback": "环回模式（自测）",
    "waveform": "波形探测",
    "open_waveform": "打开波形窗口",
    "firmware": "固件",
    "flash_fw": "烧录固件...",
    "filter": "显示过滤",
    "filter_id": "CAN ID (逗号分隔)",
    "filter_show": "仅显示",
    "filter_hide": "排除",
    "filter_off": "关闭",
    "msg_filter": "报文过滤",
    "msg_filter_id": "CAN ID (逗号分隔)",
    "no_filter": "无过滤规则",
    "trace": "报文追踪",
    "pause": "⏸ 暂停",
    "resume": "▶ 继续",
    "clear": "✕ 清空",
    "delete": "✕ 删除",
    "col_no": "序号", "col_time": "时间", "col_id": "CAN ID",
    "col_type": "类型", "col_dlc": "DLC", "col_data": "数据", "col_ch": "方向",
    "type_std": "标准", "type_ext": "扩展", "type_err": "错误",
    "msgs": "条",
    "composer": "报文编辑",
    "can_id": "CAN ID (十六进制)",
    "frame_type": "帧类型",
    "std_frame": "标准帧 (11-bit)",
    "ext_frame": "扩展帧 (29-bit)",
    "rtr_frame": "远程帧 (RTR)",
    "dlc": "DLC",
    "data_hex": "数据 (十六进制, 空格分隔)",
    "send_once": "单次发送",
    "send_err": "发送错误帧",
    "send_err_log": "发送错误帧",
    "send_rtr_log": "发送远程帧",
    "send_fail": "发送失败",
    "data_inc": "数据自增",
    "cycle": "周期发送",
    "interval": "间隔",
    "start_cycle": "▶ 开始周期",
    "stop_cycle": "⏹ 停止周期",
    "sent": "已发送:",
    "presets": "快速预设",
    "preset_rpm": "OBD-II 转速 (0x7DF)",
    "preset_speed": "OBD-II 车速 (0x7DF)",
    "preset_vin": "OBD-II VIN (0x7DF)",
    "preset_coolant": "OBD-II 冷却液 (0x7DF)",
    "preset_tpms": "TPMS 右前轮 (0x601)",
    "detail": "信号详情",
    "raw_msg": "原始报文",
    "decoded": "解码信号",
    "d_id": "ID:",
    "d_type": "类型:",
    "d_dlc": "DLC:",
    "d_data": "数据:",
    "d_time": "时间:",
    "d_err": "错误帧 — 无信号数据",
    "d_empty": "空帧 (DLC=0)",
    "w_paused": "已暂停",
    "w_stopped": "已停止",
    "w_placeholder": "波形采集未启动。\n\n连接带 ADC 的 CAN 探测器，\n点击'采集'开始采样。",
    "w_diff": "差分",
    "wave_title": "波形探测",
    "wave_rate": "采样率:",
    "wave_ch": "通道:",
    "wave_cap": "▶ 采集",
    "wave_pause": "⏸ 暂停",
    "wave_stop": "停止",
    "wave_idle": "空闲",
    "wave_capturing": "采集中...",
    "log": "日志 / 错误",
    "menu_device": "设备",
    "menu_connect": "连接",
    "menu_disconnect": "断开",
    "menu_exit": "退出",
    "menu_view": "视图",
    "menu_clear_msgs": "清除报文",
    "menu_clear_log": "清除日志",
    "menu_waveform": "波形窗口",
    "menu_device_bar": "设备栏",
    "menu_send": "发送面板",
    "menu_detail": "信号详情",
    "menu_log": "日志面板",
    "menu_settings": "设置",
    "menu_lang": "语言",
    "menu_lang_en": "English",
    "menu_lang_zh": "中文",
    "menu_help": "帮助",
    "menu_about": "关于 open-canoe",
    "no_device": "未找到设备",
    "conn_failed": "连接失败",
    "about": ("open-canoe — 开源 CAN 总线分析仪\n版本 0.3.0\n\n"
              "基于 STM32 硬件探测器的企业级 CAN 总线分析工具。\n\n"
              "替代 ZCANPRO 等商业工具。"),
    "flash_title": "烧录固件",
    "flash_select": "选择 MCU 型号:",
    "flash_info_f103": "STM32F103C8T6 — Blue Pill\n  1路CAN, 64KB Flash, USB CDC",
    "flash_info_f407": "STM32F407VET6 — Black Board\n  2路CAN, 512KB Flash, USB CDC",
    "flash_steps": ("烧录步骤：\n1. 将 ST-Link 连接到开发板\n"
                    "2. 安装 arm-none-eabi-gcc 和 OpenOCD\n"
                    "3. 编译: cd firmware && make -f Makefile.f103\n"
                    "4. 烧录: make -f Makefile.f103 flash\n\n"
                    "固件源码见 firmware/ 目录。"),
}

EN = {
    "title": "open-canoe",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "connecting": "Connecting...",
    "connected": "● Connected",
    "disconnected": "● Disconnected",
    "mcu": "MCU Target",
    "com_port": "COM Port",
    "connection": "Connection",
    "can_settings": "CAN Settings",
    "bitrate": "Bitrate",
    "silent": "Silent mode (listen only)",
    "loopback": "Loopback mode (self-test)",
    "waveform": "Waveform Probe",
    "open_waveform": "Open Waveform Window",
    "firmware": "Firmware",
    "flash_fw": "Flash Firmware...",
    "filter": "Display Filter",
    "filter_id": "CAN ID (comma-sep)",
    "filter_show": "Show only",
    "filter_hide": "Hide these",
    "filter_off": "OFF ",
    "msg_filter": "Msg Filter",
    "msg_filter_id": "CAN ID (comma-sep)",
    "no_filter": "No filter active",
    "trace": "Message Trace",
    "pause": "⏸ Pause",
    "resume": "▶ Resume",
    "clear": "✕ Clear",
    "delete": "✕ Delete",
    "col_no": "No", "col_time": "Time", "col_id": "CAN ID",
    "col_type": "Type", "col_dlc": "DLC", "col_data": "Data", "col_ch": "Dir",
    "type_std": "STD", "type_ext": "EXT", "type_err": "ERR",
    "msgs": "msgs",
    "composer": "Message Composer",
    "can_id": "CAN ID (hex)",
    "frame_type": "Frame Type",
    "std_frame": "Standard (11-bit)",
    "ext_frame": "Extended (29-bit)",
    "rtr_frame": "Remote (RTR)",
    "dlc": "DLC",
    "data_hex": "Data (hex, space-separated)",
    "send_once": "Send Once",
    "send_err": "Send Error Frame",
    "send_err_log": "Sent error frame",
    "send_rtr_log": "Sent remote frame",
    "send_fail": "Send failed",
    "data_inc": "Auto inc",
    "cycle": "Cycle Scheduler",
    "interval": "Interval",
    "start_cycle": "▶ Start Cycle",
    "stop_cycle": "⏹ Stop Cycle",
    "sent": "Sent:",
    "presets": "Quick Presets",
    "preset_rpm": "OBD-II RPM (0x7DF)",
    "preset_speed": "OBD-II Speed (0x7DF)",
    "preset_vin": "OBD-II VIN (0x7DF)",
    "preset_coolant": "OBD-II Coolant (0x7DF)",
    "preset_tpms": "TPMS Front Right (0x601)",
    "detail": "Signal Details",
    "raw_msg": "Raw Message",
    "decoded": "Decoded Signals",
    "d_id": "ID:",
    "d_type": "Type:",
    "d_dlc": "DLC:",
    "d_data": "Data:",
    "d_time": "Time:",
    "d_err": "Error frame — no signal data",
    "d_empty": "Empty frame (DLC=0)",
    "w_paused": "Paused",
    "w_stopped": "Stopped",
    "w_placeholder": "Waveform capture not started.\n\nConnect a CAN probe with ADC support,\nthen click Capture to begin sampling.",
    "w_diff": "Differential",
    "wave_title": "Waveform Probe",
    "wave_rate": "Rate:",
    "wave_ch": "Channel:",
    "wave_cap": "▶ Capture",
    "wave_pause": "⏸ Pause",
    "wave_stop": "Stop",
    "wave_idle": "Idle",
    "wave_capturing": "Capturing...",
    "log": "Log / Errors",
    "menu_device": "Device",
    "menu_connect": "Connect",
    "menu_disconnect": "Disconnect",
    "menu_exit": "Exit",
    "menu_view": "View",
    "menu_clear_msgs": "Clear Messages",
    "menu_clear_log": "Clear Log",
    "menu_waveform": "Waveform Window",
    "menu_device_bar": "Device Bar",
    "menu_send": "Send Panel",
    "menu_detail": "Signal Details",
    "menu_log": "Log Panel",
    "menu_settings": "Settings",
    "menu_lang": "Language",
    "menu_lang_en": "English",
    "menu_lang_zh": "中文",
    "menu_help": "Help",
    "menu_about": "About open-canoe",
    "no_device": "No Device Found",
    "conn_failed": "Connection Failed",
    "about": ("open-canoe — Open CAN Bus Analyzer\nVersion 0.3.0\n\n"
              "Enterprise-grade CAN bus analysis tool\nwith STM32 hardware probe.\n\n"
              "Replaces proprietary tools like ZCANPRO."),
    "flash_title": "Flash Firmware",
    "flash_select": "Select MCU target:",
    "flash_info_f103": "STM32F103C8T6 — Blue Pill\n  1x CAN, 64KB Flash, USB CDC",
    "flash_info_f407": "STM32F407VET6 — Black Board\n  2x CAN, 512KB Flash, USB CDC",
    "flash_steps": ("To flash firmware:\n1. Connect ST-Link to the board\n"
                    "2. Install arm-none-eabi-gcc and OpenOCD\n"
                    "3. Build: cd firmware && make -f Makefile.f103\n"
                    "4. Flash: make -f Makefile.f103 flash\n\n"
                    "See firmware/ directory for source code."),
}

# _current = EN
_current = ZH

def L() -> dict: return _current

def set_lang(code: str) -> None:
    global _current
    _current = ZH if code == "ZH" else EN

def lang_code() -> str: return "ZH" if _current is ZH else "EN"
