"""
Protocol constants — direct Python port of hardware/inc/protocol.h.
"""

PROTOCOL_MAGIC_HEADER = 0xA5
PROTOCOL_FRAME_HEADER_SIZE = 6
PROTOCOL_FRAME_FOOTER_SIZE = 3
PROTOCOL_FRAME_OVERHEAD = PROTOCOL_FRAME_HEADER_SIZE + PROTOCOL_FRAME_FOOTER_SIZE
PROTOCOL_FRAME_DATA_MAX = 256
PROTOCOL_FRAME_TOTAL_MAX = PROTOCOL_FRAME_OVERHEAD + PROTOCOL_FRAME_DATA_MAX
PROTOCOL_END_MAGIC = 0x5A
PROTOCOL_VERSION_MAJOR = 1
PROTOCOL_VERSION_MINOR = 0


class Command:
    """Command codes matching protocol_cmd_t."""
    GET_INFO = 0x01
    GET_CAPABILITIES = 0x02
    GET_STATUS = 0x03
    GET_ADC_STATUS = 0x04
    CAN_SET_BAUDRATE = 0x10
    CAN_SET_MODE = 0x11
    CAN_SET_FILTER = 0x12
    ADC_SET_SAMPLING = 0x20
    COMM_SET_INTERFACE = 0x28
    CAN_START_LISTEN = 0x30
    CAN_STOP_LISTEN = 0x31
    ADC_START_SAMPLE = 0x32
    ADC_STOP_SAMPLE = 0x33
    CAN_SEND_FRAME = 0x34
    SYSTEM_RESET = 0x3F

    # Responses / Notifications
    INFO_RESPONSE = 0x81
    CAPABILITIES_RESPONSE = 0x82
    STATUS_RESPONSE = 0x83
    ADC_STATUS_RESP = 0x84
    CAN_FRAME_UP = 0x90
    ADC_DATA_UP = 0x91
    ERROR_NOTIFY = 0x92
    DEVICE_HEARTBEAT = 0x93
    ACK = 0xA0
    NACK = 0xA1

    INVALID = 0xFF


class ErrorCode:
    NONE = 0x00
    INVALID_CMD = 0x01
    INVALID_PARAM = 0x02
    CRC_MISMATCH = 0x03
    BUFFER_OVERFLOW = 0x04
    TIMEOUT = 0x05
    CAN_BUS_OFF = 0x10
    CAN_ERROR_PASSIVE = 0x11
    CAN_TX_FAILED = 0x12
    CAN_RX_OVERRUN = 0x13
    ADC_NOT_AVAILABLE = 0x20
    ADC_OVERRUN = 0x21
    COMM_TX_FAILED = 0x30
    COMM_RX_OVERRUN = 0x31
    NOT_INITIALIZED = 0x40
    ALREADY_RUNNING = 0x41
    HARDWARE_FAULT = 0xFF


class CANMode:
    NORMAL = 0x00
    LISTEN_ONLY = 0x01
    LOOPBACK = 0x02
    LOOPBACK_SILENT = 0x03


class CommInterface:
    USART = 0x00
    USB_CDC = 0x01


class Capability:
    ADC = 1 << 0
    USB_CDC = 1 << 1
    MULTI_CAN = 1 << 2
    TIMESTAMP_US = 1 << 3


class CANFilterMode:
    ID_MASK = 0x00
    ID_LIST = 0x01


class CANFilterScale:
    S_16BIT = 0x00
    S_32BIT = 0x01


class CANFrameFlag:
    """bit definitions for can_frame_up_t.flags"""
    IDE = 1 << 0
    RTR = 1 << 1
    ERROR_FRAME = 1 << 2


class ADCMode:
    ADC_HARDWARE = 0
    LOGIC_LEVEL = 1


class ErrorSource:
    CAN = 0
    ADC = 1
    COMM = 2
    SYSTEM = 3


# CAN error bitmask flags
CAN_ERR_CRC = 1 << 0
CAN_ERR_BIT_STUFFING = 1 << 1
CAN_ERR_ACK = 1 << 2
CAN_ERR_FORM = 1 << 3
CAN_ERR_BUS_OFF = 1 << 4
CAN_ERR_PASSIVE = 1 << 5
CAN_ERR_WARNING = 1 << 6
CAN_ERR_RX_OVERRUN = 1 << 7

# Struct sizes for payload packing
SIZEOF_DEVICE_INFO_RESP = 72
SIZEOF_CAPABILITIES_RESP = 12
SIZEOF_STATUS_RESP = 8
SIZEOF_CAN_FRAME_UP = 19
SIZEOF_ADC_DATA_UP_BASE = 14  # without variable samples[]
SIZEOF_CAN_SEND_FRAME = 15
SIZEOF_CAN_SET_BAUDRATE = 5
SIZEOF_CAN_SET_MODE = 2
SIZEOF_CAN_SET_FILTER = 18
SIZEOF_ADC_SET_SAMPLING = 6
SIZEOF_COMM_SET_INTERFACE = 1
SIZEOF_ERROR_NOTIFY = 8
SIZEOF_ACK_RESP = 2
SIZEOF_DEVICE_HEARTBEAT = 36

# Text labels for commands (for logging/display)
CMD_NAMES = {
    0x01: "GET_INFO", 0x02: "GET_CAPABILITIES", 0x03: "GET_STATUS",
    0x04: "GET_ADC_STATUS", 0x10: "CAN_SET_BAUDRATE", 0x11: "CAN_SET_MODE",
    0x12: "CAN_SET_FILTER", 0x20: "ADC_SET_SAMPLING", 0x28: "COMM_SET_INTERFACE",
    0x30: "CAN_START_LISTEN", 0x31: "CAN_STOP_LISTEN", 0x32: "ADC_START_SAMPLE",
    0x33: "ADC_STOP_SAMPLE", 0x34: "CAN_SEND_FRAME", 0x3F: "SYSTEM_RESET",
    0x81: "INFO_RESPONSE", 0x82: "CAPABILITIES_RESP", 0x83: "STATUS_RESPONSE",
    0x84: "ADC_STATUS_RESP", 0x90: "CAN_FRAME_UP", 0x91: "ADC_DATA_UP",
    0x92: "ERROR_NOTIFY", 0x93: "DEVICE_HEARTBEAT", 0xA0: "ACK", 0xA1: "NACK",
}
